console.log("**************map()*****************");
const array_numbers = [ 20, 11, 40, 25, 23, 11, 9, 31, 60, 2, 19 ];
 console.log("Original array");
console.log(array_numbers);
 var b=array_numbers.map((value)=> value+10);
 console.log("=====after adding 10=======");
 console.log(b);
console.log("=======square =========");
var b=array_numbers.map((value)=> value*value);
console.log(b);
console.log("=======adding index with respect to element=====");
var b=array_numbers.map((value,index)=> value+index);
console.log(b);
console.log("**************filter()*****************");
console.log("Original array");
console.log(array_numbers);
var c=array_numbers.filter((value)=>value>50);
console.log("=======value>50=======");
console.log(c);
console.log("=======even no=======");
var c=array_numbers.filter((value)=>value%2==0);
console.log(c);
console.log("=======odd no=======");
var c=array_numbers.filter((value)=>value%1==0);
console.log(c);
console.log("=======divisible by 5=======");
var c=array_numbers.filter((value)=>value%5==0);
console.log(c);
console.log("======20=<value>=50=======");
var c=array_numbers.filter((value)=>(value>20 && value<50));
console.log(c);
console.log("**************reduce()*****************");
console.log("=====sum of all element========");
var c=array_numbers.reduce((total,value)=>total+value);
console.log(c);
console.log("=======sum of even no=======");
var c=array_numbers.filter((value)=>value%2==0);
var d=c.reduce((total,value)=>  total+value);
console.log(d);